### ISSUE TITLE
Access removed

### ISSUE THREAD

**Issue by minapre** [bareblackfoot/Object2HabitatMap#1]
please share the top-down maps.

**Comment by bareblackfoot** [comment]
I updated the link :D

**Comment by minapre** [comment]
Access Denied
![Screenshot from 2024-04-09 10-46-21](https://github.com/bareblackfoot/Object2HabitatMap/assets/163130454/c56e5c27-1221-44c5-8302-8dbdd4658e4b)

**Comment by bareblackfoot** [comment]
try again now

**Comment by Yuuraa** [comment]
Hi, thank you for this great work!
I'm working on a spatial QA benchmark using HM3D-Semantics scenes, and I found that the pre-generated top-down maps (especially the region maps and render_config.pkl) would be incredibly useful for my project. Could you please grant access to the Google Drive link in the README? I'd really appreciate it. Thank you!
